### ISSUE TITLE
KeyError: 'amr_parse' 

### ISSUE THREAD

**Issue by vyass612** [IBM/LOA#15]
Not sure what this error means. Kindly suggest a solution. I executed the recommended AMR-CSLOGIC installation scripts and using flask app to run the model.

```
Found 32 observations
Mincount:  8
Loaded cache from ./cache/amr_cache.pkl len: 241
 47%|███████        | 15/32 [00:02<00:02,  5.69it/s]
Traceback (most recent call last):
  File "train.py", line 88, in <module>
    loa_agent.extract_fact2logic(difficulty_level=args.difficulty_level,
  File "/home/vboxuser/loa/loa_agent.py", line 633, in extract_fact2logic
    get_verbnet_preds_from_obslist(
  File "/home/vboxuser/loa/amr_parser.py", line 60, in get_verbnet_preds_from_obslist
    rest_amr.obs2facts(obs_text,
  File "/home/vboxuser/loa/amr_parser.py", line 380, in obs2facts
    ret = self.text2amr(text)
  File "/home/vboxuser/loa/amr_parser.py", line 147, in text2amr
    self.cache[sent] = ret[self.json_key][0]
KeyError: 'amr_parse'
```

**Comment by daiki-kimura** [comment]
Sorry for late reply. it uses cache not the server. 
and i cannot reproduce it from only these information
